import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const eUkraineMediumSans = localFont({
  src: "./fonts/e-Ukraine-Medium.ttf",
  variable: "--font-e-ukraine-medium",
  weight: "500",
});

const eUkraineRegularSans = localFont({
  src: "./fonts/e-Ukraine-Regular.ttf",
  variable: "--font-e-ukraine-regular",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${eUkraineMediumSans.variable} ${eUkraineRegularSans.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
